name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend

      # 新增的敏感信息替换步骤 (关键修复点)
      - name: Replace Secrets
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ALLOWED_USER: ${{ secrets.ALLOWED_USER }}
        run: |
          # 注意路径要根据实际构建目录调整
          sed -i "s/CLIENT_ID_PLACEHOLDER/$CLIENT_ID/g" frontend/build/*.html  # ← 关键路径修正
          sed -i "s/CLIENT_SECRET_PLACEHOLDER/$CLIENT_SECRET/g" frontend/build/auth.html
          sed -i "s/ALLOWED_USER_PLACEHOLDER/$ALLOWED_USER/g" frontend/build/static/js/*.js  # ← 匹配打包后的JS文件

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build  # 必须与替换后的路径一致
          publish_branch: gh-pages
