---
name: Login Verification
on:
  workflow_dispatch:
    inputs:
      username:
        description: 用户名
        required: true
      password:
        description: 密码
        required: true
jobs:
  verify-login:
    runs-on: ubuntu-latest
    steps:
      - name: 验证登录
        id: login_check
        run: >
          if [[ "${{ github.event.inputs.username }}" == "${{ secrets.ADMIN_USERNAME
          }}" && "${{ github.event.inputs.password }}" == "${{
          secrets.ADMIN_PASSWORD }}" ]]; then
            echo "验证成功: 用户名和密码正确"
            echo "login_status=success" >> $GITHUB_ENV
          else
            echo "验证失败: 用户名或密码错误"
            echo "login_status=failure" >> $GITHUB_ENV
            exit 1
          fi
      - name: 设置输出结果
        run: echo "result=${{ env.login_status }}"
      - name: 输出验证状态
        run: echo "登录验证结果为= ${{ env.login_status }}"
