name: Login Verification

on:
  workflow_dispatch: # 手动触发
    inputs:
      username:
        description: "用户名"
        required: true
      password:
        description: "密码"
        required: true

jobs:
  verify-login:
    runs-on: ubuntu-latest
    steps:
      - name: 验证登录
        run: |
          if [[ "${{ github.event.inputs.username }}" == "${{ secrets.ADMIN_USERNAME }}" && "${{ github.event.inputs.password }}" == "${{ secrets.ADMIN_PASSWORD }}" ]]; then
            echo "登录成功"
          else
            echo "用户名或密码错误"
            exit 1
          fi
